name: Update imslib.min.js

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update file and create PR if needed
      uses: actions/github-script@v7
      with:
        script: |
          const axios = require('axios');
          const { execSync } = require('child_process');
          const fs = require('fs');
          const { GitHub } = require('@actions/github');
          const github = new GitHub(process.env.GITHUB_TOKEN);
          const context = github.context;

          const main = async () => {
            const response = await axios.get('https://auth.services.adobe.com/imslib/imslib.min.js');
            const lastModified = new Date(response.headers['last-modified']);
            const now = new Date();
            const diffHours = Math.ceil((now - lastModified) / 1000 / 60 / 60);
            console.log(`imslib.min.js last modified: ${lastModified}. Last modified ${diffHours} hours ago <= 24H, means new PR created.`);

            if (diffHours <= 24) {
              console.log("Diff detected in the last 24h, creating PR.")
              const header = `// Last modified ${lastModified.toISOString()}\n// Build at ${new Date().toISOString()}\n`;
              fs.writeFileSync('libs/deps/imslib.min.js', header + response.data);
            
              execSync('git config --global user.name "GitHub Action"');
              execSync('git config --global user.email "action@github.com"');
              execSync('git checkout stage');
              execSync('git branch -D update-imslib');
              execSync('git checkout -b update-imslib');
              execSync('git add libs/deps/imslib.min.js');
              execSync('git commit -m "Update imslib.min.js"');
              execSync('git push --force origin update-imslib');

              await github.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'Update imslib.min.js',
                head: 'update-imslib',
                base: 'stage',
                body: [
                  '## Description',
                  'Update imslib.min.js to the latest version',
                  '',
                  '## Related Issue',
                  'Resolves: NO TICKET - AUTO CREATED PR.',
                  '',
                  '## Testing instructions',
                  '1. Signing in should still function',
                  '2. Signing out should still work',
                  '3. Regression tests on all consumers',
                  '',
                  '## Test URLs',
                  '**Acrobat:**',
                  '- Before: https://www.stage.adobe.com/acrobat/online/sign-pdf.html?martech=off',
                  '- After: https://www.stage.adobe.com/acrobat/online/sign-pdf.html?martech=off&milolibs=update-imslib--milo--adobecom',
                  '',
                  '**BACOM:**',
                  '- Before: https://business.stage.adobe.com/fr/customer-success-stories.html?martech=off',
                  '- After: https://business.stage.adobe.com/fr/customer-success-stories.html?martech=off&milolibs=update-imslib--milo--adobecom',
                  '',
                  '**CC:**',
                  '- Before: https://main--cc--adobecom.hlx.live/?martech=off',
                  '- After: https://main--cc--adobecom.hlx.live/?martech=off&milolibs=update-imslib--milo--adobecom',
                  '',
                  '**Homepage:**',
                  '- Before: https://main--homepage--adobecom.hlx.page/homepage/index-loggedout?martech=off',
                  '- After: https://main--homepage--adobecom.hlx.page/homepage/index-loggedout?martech=off&milolibs=update-imslib--milo--adobecom',
                  '',
                  '**Blog:**',
                  '- Before: https://main--blog--adobecom.hlx.page/',
                  '- After: https://main--blog--adobecom.hlx.page/?milolibs=update-imslib--milo--adobecom',
                  '',
                  '**Milo:**',
                  '- Before: https://main--milo--adobecom.hlx.page/ch_de/drafts/ramuntea/gnav-refactor?martech=off',
                  '- After: https://update-imslib--milo--adobecom.hlx.page/ch_de/drafts/ramuntea/gnav-refactor?martech=off'
                ].join('\n')
              });
            }
          }
          main()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}